### ISSUE TITLE
Initial thoughts on DB Schema

### ISSUE THREAD

**Issue by MichaelSchwar3** [jprpich/trellapp#1]
Fix Home/MVP page

Username
Do we need both username and e-mail or just one?

Boards
Do we need to call the foreign key owner? I would make the argument to call it user_id to avoid confusion of “what did i call it?” when making the associations

Lists
You have this position column which can work fine. However, what if we delete something in the middle? We would then have to go through every item in the list and re-assign position. 
What I would recommend is putting two foreign keys of previous_id and next_id so that we would only have to modify 2 items at most

Cards
Same thing as lists
Not sure why we need the combination list_id and position to be unique?

Board_shares
Is this something that can be collapsed into the boards table?

Comments
Author_id to user_id

Good schema, but a few things we'll have to modify in order to make your life easier moving forward. Let me know if you want to discuss any of the feedback above.

**Comment by jprpich** [comment]
hey ! yes thanks for the feedback ... i would like to discuss this... when
is a good time?

thanks

**Comment by MichaelSchwar3** [comment]
Do you want to discuss at 3:45 today? Or towards the end of lunch time tomorrow?

**Comment by jprpich** [comment]
End lunch tomorow is perfect.

**Comment by jprpich** [comment]
All changes have been made.
