### ISSUE TITLE
Auth 1/24/19

### ISSUE THREAD

**Issue by MichaelSchwar3** [jprpich/trellapp#3]
Nice job on the auth portion so far!

Couple of things I've noticed

- [x] Need to finish CSSing the splash page

- [x] Demo user doesn't work in Heroku. I think you need to seed the DB in heroku

- [x] Your example e-mail is a little odd, perhaps something more generic like email@domain.com . At the very least, remove the extra "n" from "nnyc" Or you can use dana.scully@fbi.gov like from the real app :)

Awesome job thus far!

**Comment by jprpich** [comment]
perfect... all complete
